text/0014-improve-locking-mechanism-for-parachains.md

If this is accepted, I plan to implement this to close https://github.com/paritytech/polkadot/issues/7539
Draft PR for Polkadot https://github.com/paritytech/polkadot/pull/7560

Improve locking mechanism for parachains

---

.github/workflows/rfc-action.yml

It handles missing permissions to merge/close PRs a little more gracefully.

Update rfc-action to v0.0.4

---

.github/workflows/rfc-action.yml

It changes the merging method from REST github API to graphql, which contains more information when failing.

Update rfc-action to v0.0.5

---

text/0008-parachain-bootnodes-dht.md

[Rendered](https://github.com/tomaka/RFCs-1/blob/rfc-8/text/0008-parachain-bootnodes-dht.md).

Store parachain bootnodes in relay chain DHT

---

text/0000-one-transaction-per-notification.md
text/0056-one-transaction-per-notification.md

[Rendered](https://github.com/tomaka/RFCs-1/blob/one-tx-per-notif/text/0056-one-transaction-per-notification.md)
This RFC is pretty small, and I expect it to be pretty uncontroversial. Just because something is currently designed a certain way doesn't mean that it is so for a good reason, and sometimes, like in this RFC, things just need to be cleaned up.

Enforce one transaction per notification in the networking

---

.github/workflows/rfc-referenda-notifications.yml
README.md

It was improperly set to run every minute after 11. I changed it to run every weekday only once after 12.
Also, added status badge for the job in the Readme so we can preview there that the job is running:
[![RFC Cron](https://github.com/polkadot-fellows/RFCs/actions/workflows/rfc-referenda-notifications.yml/badge.svg)](https://github.com/polkadot-fellows/RFCs/actions/workflows/rfc-referenda-notifications.yml)

Fixed issue with RFC-Cron

---

text/0000-storage-proof-size-hostfunction.md
text/0043-storage-proof-size-hostfunction.md

https://github.com/paritytech/polkadot-sdk/pull/1462 has been open for a while and is now well-reviewed. Opening an RFC since it introduces a new host function that is relevant for parachains and light-clients.

Introduce `storage_proof_size` Host Function for Improved Parachain Block Utilization

---

text/0042-extrinsics-state-version.md

This RFC proposes adding `system_version` and remove `state_version` from `RuntimeVersion` object. This makes it possible to use `StateVersion::V1` for both Storage and Extrinsic root derivations

Introduce System version to RuntimeVersion object

---

.github/scripts/build-mdbook-summary.js
.github/workflows/mdbook.yml

- Closes https://github.com/polkadot-fellows/RFCs/issues/71
- This affects only the sidebar of the mdBook.

mdBook: Strip down links in RFCs titles

---

text/0057-nodes-capabilities-discovery.md
text/0059-nodes-capabilities-discovery.md

[Rendered](https://github.com/tomaka/RFCs-1/blob/rfc57/text/0059-nodes-capabilities-discovery.md)

Add a discovery mechanism for nodes based on their capabilities

---

.github/workflows/rfc-referenda-notifications.yml

Changed the time to run **every day at 12:00** (UTC)
Updated the version to 0.0.8 which fixes the bug with the referenda url comment being wrongly formatted

fixed rfc-action cron job

---

.github/workflows/rfc-action.yml

This includes https://github.com/paritytech/rfc-action/pull/34 which takes into consideration successful RFCs.
When a RFC closed after the last run, it will comment on the open PR (if it is still open) that the RFC has been closed and how to trigger the bot to merge the PR.
If it is succesfull, we can automate it to simply close the PRs without human input.
Also, updated actions/create-github-app-token to latest (version `1.8.1`)

updated rfc-action to 0.1.0 (inform on closed referendas)

---

.github/workflows/rfc-referenda-notifications.yml

When doing #80 I got confused and updated the wrong action (which uses the same dependency).
This one updates the RFC action for the cron job
---
When a RFC closes after the last run, it will comment on the open PR (if it is still open) that the RFC has been closed and how to trigger the bot to merge the PR.
If it is succesfull, we can automate it to simply close the PRs without human input.
- Also, updated cron job to run at mid day and at end of the day so we can capture new RFCs more often.
- `v0.1.1` also has a fix for a problem with LFS files not being downloaded by the GitHub Actions that was discovered and fixed in paritytech/rfc-action#37 by @rzadp.

rfc-cron: updated cron to v0.1.1

---

text/0000-session-keys-runtime-api.md
text/0048-session-keys-runtime-api.md

This RFC changes the `SessionKeys` runtime api to support generating a proof of ownership of the generated session keys.

Generate ownership proof for `SessionKeys`

---

text/0000-dht-record-creation-time.md
text/0091-dht-record-creation-time.md

This adds a new creation time for authority discovery records stored in the DHT. 
This RFC has already an implementation in polkadot-sdk here: https://github.com/paritytech/polkadot-sdk/pull/3786

Add creation time for DHT authority discovery records

---

text/0078-merkleized-metadata.md

This augments the `RFC78` with some clarification on the front of how to include the data into the extrinsic.

Merkleized Metadata: Bring some clarification for the extrinsic inclusion

---

text/0108-xcm-remove-testnet-ids.md

Testnets are not stable and shouldn't be included in the XCM language. They should be able to be specified with `NetworkId::ByGenesis`.

[XCM]: Remove NetworkIds for testnets

---

text/0101-xcm-transact-allow-unlimited-weight.md
text/0101-xcm-transact-remove-max-weight-param.md

This is a continuation of https://github.com/polkadot-fellows/xcm-format/pull/55 following the migration of XCM RFCs to this repo.
Remove the `require_weight_at_most: Weight` parameter of the Transact instruction.
The UX of using Transact is not great, and one part of the problem is guesstimating this require_weight_at_most.
We've seen multiple Transacts on-chain failures caused by the "incorrect" use or the parameter. In practice, this parameter only adds UX overhead. Use cases fall in one of two categories:
1. Unpaid execution of Transacts - in these cases the require_weight_at_most is not really useful, caller doesn't have to pay for it, and on the call site it either fits the block or not;
2. Paid execution of single Transact - the weight to be spent by the Transact is already covered …

Remove `require_weight_at_most` from XCM Transact

---

.github/scripts/build-mdbook-summary.js

With a recent PR that has spaces in the RFC filename, the RFC book generation script started failing - this fixes it.

Handle filenames with whitespaces in the RFC book

---

text/0100-xcm-multi-type-asset-transfer.md

This is a continuation of https://github.com/polkadot-fellows/xcm-format/pull/63 following the migration of XCM RFCs to this repo.
This RFC proposes a new instruction that provides a way to initiate asset transfers which transfer multiple types (teleports, local-reserve, destination-reserve) of assets, on remote chains using XCM alone.
The currently existing instructions are too opinionated and force each XCM asset transfer to a single transfer type (teleport, local-reserve, destination-reserve). This results in inability to combine different types of transfers in single transfer which results in overall poor UX when trying to move assets across chains.
```rust
// pay remote fees with ROCs
let remote_fees = Some(
AssetTransferFilter::ReserveWithdraw(
AssetFilter::Wild(AllOf { id: …
```

Introduce new XCM instruction: `InitiateAssetsTransfer` for complex asset transfers

---

text/0105-xcm-improved-fee-mechanism.md

Moved from https://github.com/polkadot-fellows/xcm-format/pull/53.
The idea is to extend the current XCM fee mechanism to support in principle delivery fees, but potentially other types of fees as well.
This is accomplished by having two additions:
- `PayFees` instruction
- A `fees` register, where fees go and stay there until the end of execution. Crucially, separate from the `holding` register

[XCM]: Improved fee mechanism

---

text/0102-introduce-core-index-commitment.md
text/0103-introduce-core-index-commitment.md

Following the discussion on https://github.com/polkadot-fellows/RFCs/issues/92, this is a proposal to introduce the required core index commitments to make elastic scaling work securely with open collator sets.

Constrain parachain block validity on a specific core

---

text/0009-improved-net-light-client-requests.md

[Rendered](https://github.com/tomaka/RFCs-1/blob/rfc-9/text/0009-improved-net-light-client-requests.md)
This is a continuation of https://github.com/w3f/PPPs/pull/10
Compared to https://github.com/w3f/PPPs/pull/10, I've changed my mind about truncated proofs. I think that it's better if the client can fully verify the proofs that are returned even when the response size limit would be exceeded. This also means that the proof  no longer needs to be deterministic, and I've removed the paragraph about this.
cc @cheme

Improved light client requests networking protocol

---

text/0135-compressed-blob-prefixes.md

[Rendered](https://github.com/s0me0ne-unkn0wn/RFCs/blob/s0me0ne/compressed-blob-prefixes/text/0135-compressed-blob-prefixes.md)

Standardize compressed blob prefixes
